#!/bin/sh -e

folder=${BWHELPER_DOCKER:-docker-creds}

case $1 in
	get)
		key=$(cat)
		folder=$(bw --nointeraction get folder "$folder" | jq -er .id)
		bw --nointeraction list items --folderid "$folder" --search "$key" \
		    | jq -er .[0].login.password
		;;
	*)
		exit 1
		;;
esac
